from oop.bus import Bus
from oop.car import Car
from oop.dataProviderDictionaryCar import DataProviderDictionaryCar
from oop.motorbike import Motorbike

car1 = Car(id="1", make="BMW", model="3.20i", color="Yellow", year="2018", price=180000, sunroof=True)
print("*****************Car1********************")
print("Car 1 Id      : {0}".format(car1.getId()))
print("Car 1 make    : {0}".format(car1.getMake()))
print("Car 1 model   : {0}".format(car1.getModel()))
print("Car 1 color   : {0}".format(car1.getColor()))
print("Car 1 year    : {0}".format(car1.getYear()))
print("Car 1 price   : {0}".format(car1.getPrice()))
print("Car 1 sunroof : {0}".format(car1.getSunroof()))
print("Car 1 price with Tax : {0}".format(car1.calculatePriceWithTax()))
print("*****************Car2********************")
car2 = Car()
car2.setId("2")
car2.setMake("Fiat")
car2.setModel("Doblo")
car2.setColor("Black")
car2.setYear("2016")
car2.setPrice(70000)
car2.setSunroof(False)
print("Car 2 Id      : {0}".format(car2.getId()))
print("Car 2 make    : {0}".format(car2.getMake()))
print("Car 2 model   : {0}".format(car2.getModel()))
print("Car 2 color   : {0}".format(car2.getColor()))
print("Car 2 year    : {0}".format(car2.getYear()))
print("Car 2 price   : {0}".format(car2.getPrice()))
print("Car 2 sunroof : {0}".format(car2.getSunroof()))
print("Car 2 price with Tax : {0}".format(car2.calculatePriceWithTax()))

print("*****************Bus1********************")
bus1 = Bus(id="3", make="Man", model="700C", color="blue", year="2015", price=500000, airSuspension=True)
print("Bus 1 Id             : {0}".format(bus1.getId()))
print("Bus 1 make           : {0}".format(bus1.getMake()))
print("Bus 1 model          : {0}".format(bus1.getModel()))
print("Bus 1 color          : {0}".format(bus1.getColor()))
print("Bus 1 year           : {0}".format(bus1.getYear()))
print("Bus 1 price          : {0}".format(bus1.getPrice()))
print("Bus 1 air suspension : {0}".format(bus1.getAirSuspension()))
print("Bus 1 price with Tax : {0}".format(bus1.calculatePriceWithTax()))
print("*****************Bus2********************")
bus2 = Bus()
bus2.setId("4")
bus2.setMake("Man")
bus2.setModel("900C")
bus2.setColor("White")
bus2.setYear("2019")
bus2.setPrice(600000)
bus2.setAirSuspension(True)

print("Bus 2 Id             : {0}".format(bus2.getId()))
print("Bus 2 make           : {0}".format(bus2.getMake()))
print("Bus 2 model          : {0}".format(bus2.getModel()))
print("Bus 2 color          : {0}".format(bus2.getColor()))
print("Bus 2 year           : {0}".format(bus2.getYear()))
print("Bus 2 price          : {0}".format(bus2.getPrice()))
print("Bus 2 air suspension : {0}".format(bus2.getAirSuspension()))
print("Bus 2 price with Tax : {0}".format(bus2.calculatePriceWithTax()))
print("*****************Motorbike1********************")
motorbike1 = Motorbike(id="5",make="Yamaha",model="YZF600",color="green",year="2019",price=80000,selfBalance=False)
print("Motorbike 1 Id             : {0}".format(motorbike1.getId()))
print("Motorbike 1 make           : {0}".format(motorbike1.getMake()))
print("Motorbike 1 model          : {0}".format(motorbike1.getModel()))
print("Motorbike 1 color          : {0}".format(motorbike1.getColor()))
print("Motorbike 1 year           : {0}".format(motorbike1.getYear()))
print("Motorbike 1 price          : {0}".format(motorbike1.getPrice()))
print("Motorbike 1 self balance   : {0}".format(motorbike1.getSelfBalance()))
print("Motorbike 1 price with Tax : {0}".format(motorbike1.calculatePriceWithTax()))
print("*****************Motorbike2********************")
motorbike2 = Motorbike()
motorbike2.setId("6")
motorbike2.setMake("Bmw")
motorbike2.setModel("1000C")
motorbike2.setColor("White")
motorbike2.setYear("2020")
motorbike2.setPrice(160000)
motorbike2.setSelfBalance(True)
print("Motorbike 2 Id             : {0}".format(motorbike2.getId()))
print("Motorbike 2 make           : {0}".format(motorbike2.getMake()))
print("Motorbike 2 model          : {0}".format(motorbike2.getModel()))
print("Motorbike 2 color          : {0}".format(motorbike2.getColor()))
print("Motorbike 2 year           : {0}".format(motorbike2.getYear()))
print("Motorbike 2 price          : {0}".format(motorbike2.getPrice()))
print("Motorbike 2 self balance   : {0}".format(motorbike2.getSelfBalance()))
print("Motorbike 2 price with Tax : {0}".format(motorbike2.calculatePriceWithTax()))


print("*****************DATA PROVIDER DICTIONARY CAR********************")
dataProviderCar = DataProviderDictionaryCar()
dataProviderCar.insert(car1)
dataProviderCar.insert(car2)
car1.setModel("5.20i")
dataProviderCar.update(car1)
dataProviderCar.delete("1")
print(dataProviderCar.getById("2"))

print("*****************CAR LIST********************")
carList = dataProviderCar.getList()
for carId,carInfo in carList.items():
    print(carInfo)
